# Generated by Django 5.0.6 on 2024-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField()),
                ('meal_cost', models.FloatField()),
                ('waiter_name', models.TextField()),
                ('tip_cost', models.FloatField()),
                ('tip_percentage', models.FloatField()),
            ],
        ),
    ]
